# Generated by Django 5.2.6 on 2025-09-25 19:44

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.train_image_path
            ),
        ),
    ]
